[package]
name = "merkle_zkp_project"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bellman = "0.9.0"
bls12_381 = "0.4.0"
rand = "0.8.5"